# Generated by Django 3.2.16 on 2023-11-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0015_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='Block',
        ),
    ]
